import nodemailer from "nodemailer";

/**
 * Star Ranker Email Engine
 * Handles automated notifications for onboarding, settlements, and security.
 */

// Mock transport for Dev environment
// In Prod, replace with Brevo/SendGrid SMTP or API
const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || "smtp.ethereal.email",
    port: parseInt(process.env.SMTP_PORT || "587"),
    secure: false,
    auth: {
        user: process.env.SMTP_USER || "dev_oracle",
        pass: process.env.SMTP_PASS || "dev_secret",
    },
});

export const sendEmail = async (to: string, subject: string, html: string) => {
    console.log(`[EMAIL-ENGINE] Queuing email to ${to}: ${subject}`);

    if (process.env.NODE_ENV === "development" || !process.env.SMTP_HOST) {
        console.log("--- EMAIL CONTENT START ---");
        console.log(html);
        console.log("--- EMAIL CONTENT END ---");
        return { success: true, mock: true };
    }

    try {
        const info = await transporter.sendMail({
            from: `"Star Ranker" <${process.env.SMTP_FROM || "noreply@starranker.io"}>`,
            to,
            subject,
            html,
        });
        return { success: true, messageId: info.messageId };
    } catch (error) {
        console.error("[EMAIL-ENGINE] Error sending email:", error);
        return { success: false, error };
    }
};

export const templates = {
    welcome: (identity: string) => ({
        subject: "ACCESS GRANTED: Star Ranker Terminal Onboarding",
        html: `
            <div style="background: #020617; color: #f8fafc; padding: 40px; font-family: 'Courier New', Courier, monospace; line-height: 1.6;">
                <div style="border: 1px solid #38bdf8; padding: 20px; border-radius: 8px; background: #0f172a;">
                    <h1 style="color: #38bdf8; text-transform: uppercase; margin-top: 0; font-size: 20px; letter-spacing: 2px;">
                        [ AUTHENTICATION SUCCESSFUL ]
                    </h1>
                    <p style="color: #94a3b8; font-size: 14px;">Oracle Handle: ${identity}</p>
                    <hr style="border: none; border-top: 1px solid #1e293b; margin: 20px 0;" />
                    
                    <p>Welcome to the Star Ranker Oracle Network. Your access to the cultural zeitgeist terminal has been initialized.</p>
                    
                    <div style="background: #020617; border-left: 4px solid #38bdf8; padding: 15px; margin: 20px 0;">
                        <p style="margin: 5px 0;"><strong>PROVISIONED TIER:</strong> Initiate</p>
                        <p style="margin: 5px 0;"><strong>INITIAL REPUTATION:</strong> 100 UNITS</p>
                        <p style="margin: 5px 0;"><strong>SECURITY STATUS:</strong> ACTIVE BETA</p>
                    </div>
                    
                    <p style="color: #38bdf8;">Your handle is now linked to the primary ranking engine.</p>
                    <p style="font-size: 12px; color: #64748b; margin-top: 30px;">
                        System sync confirmed at ${new Date().toUTCString()}
                    </p>
                </div>
            </div>
        `
    }),
    settlement: (itemName: string, payout: number, isWin: boolean) => ({
        subject: `Epoch Result: ${itemName} ${isWin ? 'PROFIT' : 'LOSS'}`,
        html: `
            <div style="background: #020617; color: #f8fafc; padding: 40px; font-family: sans-serif;">
                <h2 style="color: ${isWin ? '#10b981' : '#f43f5e'}; text-transform: uppercase;">
                    ${isWin ? 'Oracle Alignment Successful' : 'Market Divergence Detected'}
                </h2>
                <p>Stake on <strong>${itemName}</strong> has been reified.</p>
                <p>Result: <strong>${payout > 0 ? '+' : ''}${payout.toLocaleString()} units</strong></p>
                <hr style="border: none; border-top: 1px solid #1e293b; margin: 20px 0;" />
                <p style="font-size: 12px; color: #64748b;">This notification was automatically generated by the settlement worker.</p>
            </div>
        `
    })
};
