import nodemailer from "nodemailer";

/**
 * Star Ranker Email Engine
 * Handles automated notifications for onboarding, settlements, and security.
 */

// Mock transport for Dev environment
// In Prod, replace with Brevo/SendGrid SMTP or API
const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || "smtp.ethereal.email",
    port: parseInt(process.env.SMTP_PORT || "587"),
    secure: false,
    auth: {
        user: process.env.SMTP_USER || "dev_oracle",
        pass: process.env.SMTP_PASS || "dev_secret",
    },
});

export const sendEmail = async (to: string, subject: string, html: string) => {
    console.log(`[EMAIL-ENGINE] Queuing email to ${to}: ${subject}`);

    if (process.env.NODE_ENV === "development" || !process.env.SMTP_HOST) {
        console.log("--- EMAIL CONTENT START ---");
        console.log(html);
        console.log("--- EMAIL CONTENT END ---");
        return { success: true, mock: true };
    }

    try {
        const info = await transporter.sendMail({
            from: `"Star Ranker" <${process.env.SMTP_FROM || "noreply@starranker.io"}>`,
            to,
            subject,
            html,
        });
        return { success: true, messageId: info.messageId };
    } catch (error) {
        console.error("[EMAIL-ENGINE] Error sending email:", error);
        return { success: false, error };
    }
};

export const templates = {
    welcome: (name: string) => ({
        subject: "Terminal Access Granted - Welcome to Star Ranker",
        html: `
            <div style="background: #020617; color: #f8fafc; padding: 40px; font-family: sans-serif;">
                <h1 style="color: #38bdf8; text-transform: uppercase;">Oracle Identified: ${name}</h1>
                <p>Welcome to the cultural zeitgeist terminal. Your reputation units have been initialized.</p>
                <div style="border-left: 4px solid #38bdf8; padding-left: 20px; margin: 20px 0;">
                    <p><strong>Status:</strong> Active Beta</p>
                    <p><strong>Reputation:</strong> 100</p>
                    <p><strong>Balance:</strong> $10,000 (Simulated)</p>
                </div>
                <p>Deploy your influence strategically.</p>
            </div>
        `
    }),
    settlement: (itemName: string, payout: number, isWin: boolean) => ({
        subject: `Epoch Result: ${itemName} ${isWin ? 'PROFIT' : 'LOSS'}`,
        html: `
            <div style="background: #020617; color: #f8fafc; padding: 40px; font-family: sans-serif;">
                <h2 style="color: ${isWin ? '#10b981' : '#f43f5e'}; text-transform: uppercase;">
                    ${isWin ? 'Oracle Alignment Successful' : 'Market Divergence Detected'}
                </h2>
                <p>Stake on <strong>${itemName}</strong> has been reified.</p>
                <p>Result: <strong>${payout > 0 ? '+' : ''}${payout.toLocaleString()} units</strong></p>
                <hr style="border: none; border-top: 1px solid #1e293b; margin: 20px 0;" />
                <p style="font-size: 12px; color: #64748b;">This notification was automatically generated by the settlement worker.</p>
            </div>
        `
    })
};
